export { default as About } from "./About";
export { default as Base } from "./Base";
export { default as DottedSquare } from "./DottedSquare";
export { default as Experiences } from "./Experiences";
export { default as Grid } from "./Grid";
export { default as Header } from "./Header";
export { default as PanelSkill } from "./PanelSkill";
export { default as Square } from "./Square";
export { default as Work } from "./Work";
